import type { Metadata } from "next";
import localFont from 'next/font/local'

import "./globals.css";

import { ThemeProvider } from "@/app/_providers/theme-provider";
import { Toaster } from "@/shared/ui/sonner";
import TanStackQueryClientProvider from "./_providers/queryClient-provider";

const sfPro = localFont({
  src: '../shared/assets/SF-Pro.ttf', // public 폴더가 아닌 상대 경로
  variable: '--font-sf-pro',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sfPro.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanStackQueryClientProvider>
            {children}
            <Toaster position="top-right" />
          </TanStackQueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
